### PR TITLE
Update locked dependencies with `cargo update`

### PR DESCRIPTION
**Pull request by MarijnS95**
This solves some outdated dependencies like a failed crater run for a new Rust feature [1] in one of the dependencies.

[1]: https://github.com/krolli/vk-parse/issues/18#issue-861637478

### CODE REVIEW

**Comment by krolli** [comment]
For easier navigation to relevant crater run: https://crater-reports.s3.amazonaws.com/pr-65819/index.html

Now, I will be honest, I'm not entirely sure what issue is exactly. I'm not that familiar with crater and when it's used, so I looked it up. From it's readme (https://github.com/rust-lang/crater/blob/master/README.md)
> Crater is a tool to run experiments across parts of the Rust ecosystem. Its primary purpose is to detect regressions in the Rust compiler, and it does this by building a large number of crates, running their test suites and comparing the results between two versions of the Rust compiler.

That suggests to me that given crater run has either found a regression in the compiler, or ran into some old code that should have been rejected by the compiler in the past, but it wasn't until now.

Now the question is, what should we do here. Broken code is not even part of direct dependency. Also, whether `Cargo.lock` is present or not and what are its contents should also be irrelevant, which is why I'm not sold on the idea that running `cargo update` and committing new version of `Cargo.lock` is correct fix for this problem. IIRC, current version of `Cargo.lock` was created using dependency resolution with `minimal-versions` (see https://github.com/rust-lang/cargo/issues/5657). It is using old crate versions on purpose to verify that dependency versions in `Cargo.toml` are correct and work and to avoid surprises when someone uses this crate.

So, I see three possible solutions here:
- Give up on trying to verify correctness of dependencies and their version using `minimal-versions`. Considering that this crate is probably used by one or two projects at most, it might be the best solution to this, but I would prefer resorting to it only if all else fails.
- In case of compiler regression discovered by crater when running, it should be communicated with compiler people.
- In case of issue in dependency itself (I believe that would be `ring-0.14.0`), we should go along the chain and figure out which of our direct dependencies has to be updated and what is the minimum version (I'd prefer not jumping straight to latest). Sadly, I don't know what rust compiler version was used by crater and I can't reproduce it locally to test different versions.

**Comment by MarijnS95** [comment]
> That suggests to me that given crater run has either found a regression in the compiler, or ran into some old code that should have been rejected by the compiler in the past, but it wasn't until now.

I have failed to bring along the explanation from #18, as this is not based on that Crater run alone (which tests _new Rust compiler/std features_ against many existing crates - and doesn't even matter anymore since there's now a "better" solution that doesn't break existing crates but lets them chug along with slight mis-use of `.into_iter()`). Rather, when seeing `Cargo.lock` checked in that usually smells of outdated dependencies. Not that that is a problem per-se, but it seems to me that checking this in is used as a ways to state/document: "these are the known dependency versions that this has been tested with". Simply updating them with `cargo update` shows that we now have more recent versions that have been confirmed working as expected.

Testing against minimum supported versions seems like a nice feature, but I do also appreciate and sometimes prefer to test against more recent or the latest versions as well - which shouldn't break anything if semver is adhered to. That is after all what `Cargo.toml` specifies with `^` (that's the default btw!), there's no `=` to fix the version in place.

In fact it doesn't even matter when `vk-parse` is used as library, `Cargo.lock` here is only read when building within this tree and running its tests. Projects like `Ash` (that don't have `Cargo.lock` checked in) simply use the latest version when cloning or after a user manually runs `cargo update` in their local checkout.

> IIRC, current version of `Cargo.lock` was created using dependency resolution with `minimal-versions`

Looks like it, yes:

https://github.com/krolli/vk-parse/blob/b5369247e5e48ac5a5f822962beb116f1cd36733/ci/Cargo.toml#L16

Just a pity that we have to fixup the transitive `log` dependency.

> So, I see three possible solutions here:

The fourth is probably to run a `-Z minimal-versions` check in the CI, with or without `Cargo.lock` checked in. And also test against the latest versions which will automatically be selected by `^` semver as mentioned earlier, as that's what most crates will end up using automatically.

**Comment by krolli** [comment]
> The fourth is probably to run a `-Z minimal-versions` check in the CI, with or without `Cargo.lock` checked in. And also test against the latest versions which will automatically be selected by `^` semver as mentioned earlier, as that's what most crates will end up using automatically.

Good point. I don't like having `Cargo.lock` versioned, so this might be the best way to ensure things work on wider range of versions. Once all the parsing issues have been fixed, I'll probably sit down and do this (unless someone beats me to it). I would prefer that as a PR over just updating `Cargo.lock`, especially since you mentioned that `Cargo.lock` shouldn't matter.

> Rather, when seeing `Cargo.lock` checked in that usually smells of outdated dependencies. Not that that is a problem per-se, but it seems to me that checking this in is used as a ways to state/document: "these are the known dependency versions that this has been tested with". Simply updating them with `cargo update` shows that we now have more recent versions that have been confirmed working as expected.

So, I think this is the part that confused me about this PR. I assumed the goal is to provide a fix for that crater run, but considering `Cargo.lock` should not be taken into account by anything in the ecosystem, I didn't understand how updating it could fix anything. Unless that update came with changes in `Cargo.toml` as well. However, `Cargo.lock` has different meaning in this case and running `cargo update` goes against that, so I was reluctant to accept it.

> Testing against minimum supported versions seems like a nice feature, but I do also appreciate and sometimes prefer to test against more recent or the latest versions as well - which shouldn't break anything if semver is adhered to. That is after all what `Cargo.toml` specifies with `^` (that's the default btw!), there's no `=` to fix the version in place.

Problem is that most people build things with latest versions of all dependencies and unknowingly start relying on things which their semver requirements don't include. At this point, I've lost count of how many crates with broken semver requirements I've run into across various projects. Even in this tiny one, you see that manual `log` update. Before `minreq` I used `reqwest` and that required 4 such updates. And I often found this to be the case even when I set my own semver requirement to the latest version. I just find it far more likely something will be broken on older versions of dependencies than on the most recent ones, so I decided to focus on that. By its very nature, rust ecosystem pushes people towards newer versions, but it doesn't enforce `Cargo.toml` to reflect that that is what things were tested against. Until someone makes push for `minimal-versions`, this is not likely to change, unfortunately.

Anyway, if this is alright with you, I would rather reject this PR. The best solution seems to be to remove `Cargo.lock` from repository and check against minimal versions on CI. You're not the first person to be confused by this and you most likely won't be the last.

**Comment by MarijnS95** [comment]
The crater run performed check/build/test inside this repository where `Cargo.lock` is used; it didn't run on one of the dependent crates like `ash` though, where this should not have been an issue.

I agree, it seems better to remove `Cargo.lock` since:
- It is not ready by dependent libraries anyway;
- Shadowing the representation in `Cargo.toml`, which _is_ read by dependent crates, and which we **do** want to adhere to minimum version rules.

However, you'll have to figure out how to represent the `log 0.4.4` dependency with `Cargo.toml` only which is required anyway if one expects dependent crates to be able to run `-Z minimal-versions` without hassle. Running `cargo update --package log --precise 0.4.4` in the CI won't solve that. For now depending on `log = "0.4.4"` seems the easiest way to fix this for everyone - bar updating the `minreq` dependency entirely (latest is `2.3.1` - and `ron` can be bumped to `0.6.4` too). Worth noting that these are _CI_ dependencies, not the `vk-parse` library itself, but they share `Cargo.lock` and `minimal-versions` should be tested in unison.

I for one advocate towards keeping crates up to date, assuming there's usually new features and better code (more bugfixes) without breaking existing functionality if semver is adhered to. Running older crates doesn't seem too advantageous to me, if only to set a lower boundary for dependencies. That's only relevant if dependencies were hard to update (ie. native libraries that are held back on slow but stable distros) which is hardly ever the case with most crates being pure Rust and recompiled fresh from source. It might help embedded situations and those on ancient Rust compilers for similar reasons?

Perhaps it is only truly relevant when public API exposes types from other crates, à la https://github.com/dtolnay/semver-trick.

At the same time this strategy - when applied to major/minor versions - might result in increased dependency duplication (compiling the same crate on multiple versions) where most crates try to use the latest and greatest, but some crates hold back because an older version works just as well.

---

In the end I do keep telling people to take advantage of Cargo's automatic caret semver matching and omit an explicit patch version _unless they made sure that is the absolute minimum required_. It's all tricky, and I have yet to find the silver bullet.

**Pull request merged**
